import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'

import {
  allowedPortableResources,
  forbiddenPortablePatterns,
  forbiddenResourceGlobs,
  legacyPortableScripts,
  preferredPortableBuildScript,
  sensitiveKeyNames,
} from './fixtures/runtime-packaging-policy.fixture.js'

const repoRoot = process.cwd()

const policyStatement = {
  scope: 'Runtime Packaging Gate contract baseline',
  expectedGapLabel: 'expected packaging gap',
  rules: [
    'Only packaging config and script text is inspected by this test.',
    'Do not import scripts/dev-api.js.',
    'Do not read runtime/data/secrets content.',
    'Do not run package or build commands.',
    'Do not create a second runtime packaging system.',
    'Future fixes must harden the existing build-desktop-client.ps1 flow first.',
  ],
}

function readText(relativePath) {
  return fs.readFileSync(path.join(repoRoot, relativePath), 'utf8')
}

function fileExists(relativePath) {
  return fs.existsSync(path.join(repoRoot, relativePath))
}

function normalizeSlash(value) {
  return String(value).replaceAll('\\', '/')
}

function parseTauriConfig() {
  return JSON.parse(readText('src-tauri/tauri.conf.json'))
}

function flattenResources(resources) {
  if (!Array.isArray(resources)) return []
  return resources.map(String)
}

function hasRootCopy(text, rootName) {
  const escaped = rootName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
  const patterns = [
    new RegExp(`Copy-Item[\\s\\S]{0,140}\\$ROOT\\s+["']${escaped}`, 'i'),
    new RegExp(`Join-Path\\s+\\$ROOT\\s+["']${escaped}`, 'i'),
    new RegExp(`\\$ROOT\\s+["']${escaped}\\\\\\*["']`, 'i'),
  ]
  return patterns.some(pattern => pattern.test(text))
}

function scriptContainsAny(text, needles) {
  const lower = text.toLowerCase()
  return needles.some(needle => lower.includes(String(needle).toLowerCase()))
}

test('runtime packaging policy fixture defines allowlist, denylist, and baseline scripts', () => {
  assert.ok(allowedPortableResources.includes('resources/runtime/'))
  assert.ok(allowedPortableResources.includes('resources/bin/'))
  assert.ok(allowedPortableResources.includes('resources/templates/'))
  assert.ok(allowedPortableResources.includes('resources/data/ocr/ocr-config.json'))
  assert.ok(allowedPortableResources.includes('resources/data/.openclaw'))
  assert.ok(allowedPortableResources.includes('resources/data/hermes'))
  assert.ok(allowedPortableResources.includes('resources/data/claude-panel'))

  for (const required of [
    '.env',
    'relay-config.json',
    'auth.json',
    'gateway-owner.json',
    'clawpanel-device-key.json',
    '*.db',
    '*.sqlite',
    'logs',
    'sessions',
    'memories',
    'cache',
    'pid',
    'lock',
    'node_modules',
    'src-tauri/target',
    'data/',
    'uv-python/',
    'uv-tools/',
    'C:\\Users\\',
    'Documents',
    'feature-agent-runtime-orchestration-image',
    'restore-hermes',
    'superclaw-1.0.5',
    'superclaw-1.0.6',
  ]) {
    assert.ok(forbiddenPortablePatterns.includes(required), `missing forbidden pattern: ${required}`)
  }

  for (const keyName of [
    'key',
    'token',
    'secret',
    'password',
    'access_token',
    'refresh_token',
    'cookie',
    'authorization',
    'relay_config',
    'minimax_key',
    'openai_key',
    'anthropic_key',
  ]) {
    assert.ok(sensitiveKeyNames.includes(keyName), `missing sensitive key name: ${keyName}`)
  }

  assert.equal(preferredPortableBuildScript, 'scripts/build-desktop-client.ps1')
  assert.deepEqual(legacyPortableScripts, [
    'scripts/package-portable.ps1',
    'scripts/package-portable-fixed.ps1',
  ])
})

test('tauri bundle.resources must not include runtime data or local cache globs', () => {
  const tauri = parseTauriConfig()
  const resources = flattenResources(tauri.bundle?.resources)
  const forbiddenHits = resources.filter(resource => forbiddenResourceGlobs.includes(resource))

  assert.deepEqual(
    forbiddenHits,
    [],
    `${policyStatement.expectedGapLabel}: tauri bundle.resources still contains forbidden glob(s): ${forbiddenHits.join(', ')}`,
  )
})

test('portable resources must be allowlisted instead of shipping resources/data as a whole glob', () => {
  const tauri = parseTauriConfig()
  const resources = flattenResources(tauri.bundle?.resources).map(normalizeSlash)
  const wholeDataGlob = resources.find(resource => resource === 'resources/data/**/*')

  assert.equal(
    wholeDataGlob,
    undefined,
    `${policyStatement.expectedGapLabel}: resources/data cannot enter deliverables as a whole glob; sanitized data must be generated by ${preferredPortableBuildScript}`,
  )

  assert.ok(resources.some(resource => resource.startsWith('resources/runtime/')))
  assert.ok(resources.some(resource => resource.startsWith('resources/bin/')))
})

test('preferred build script contains secret and runtime-state cleanup gates', () => {
  assert.ok(fileExists(preferredPortableBuildScript), 'preferred portable build script is missing')

  const script = readText(preferredPortableBuildScript)
  for (const required of ['.env', '.env.local', 'user-memory.json']) {
    assert.ok(script.includes(required), `preferred build script must block ${required}`)
  }

  for (const required of ['logs', 'sessions', 'memories', 'cache', '.db', '.sqlite', 'pid', 'lock']) {
    assert.ok(
      scriptContainsAny(script, [required]),
      `preferred build script must contain cleanup semantics for ${required}`,
    )
  }

  for (const required of ['SanitizedTest', 'Prepare-PortableDataState', 'Clear-PackagedRuntimeArtifacts', 'Assert-CleanPackageForRelease', 'Assert-NoPackagedUserState']) {
    assert.ok(script.includes(required), `preferred build script missing packaging gate term: ${required}`)
  }
})

test('legacy portable scripts are not 1.0.7 baseline and must not copy root runtime caches', () => {
  const highRiskFindings = []

  for (const scriptPath of legacyPortableScripts) {
    if (!fileExists(scriptPath)) continue
    const script = readText(scriptPath)
    const riskyRoots = ['data', 'uv-python', 'uv-tools'].filter(rootName => hasRootCopy(script, rootName))
    if (riskyRoots.length) {
      highRiskFindings.push(`${scriptPath} copies root ${riskyRoots.join(', ')}`)
    }
  }

  assert.deepEqual(
    highRiskFindings,
    [],
    `${policyStatement.expectedGapLabel}: legacy portable scripts must not be used as the 1.0.7 baseline: ${highRiskFindings.join('; ')}`,
  )
})

test('config and packaging scripts must not reference old package or wrong branch paths', () => {
  const scannedPaths = [
    'src-tauri/tauri.conf.json',
    preferredPortableBuildScript,
    'scripts/preflight-package-audit.ps1',
    ...legacyPortableScripts,
  ]
  const forbiddenOldPackageTerms = [
    'feature-agent-runtime-orchestration-image',
    'restore-hermes',
    'superclaw-1.0.5',
    'superclaw-1.0.6',
  ]

  const hits = []
  for (const scannedPath of scannedPaths) {
    if (!fileExists(scannedPath)) continue
    const text = readText(scannedPath)
    for (const term of forbiddenOldPackageTerms) {
      if (text.includes(term)) hits.push(`${scannedPath}: ${term}`)
    }
  }

  assert.deepEqual(
    hits,
    [],
    `${policyStatement.expectedGapLabel}: old/wrong package references found: ${hits.join('; ')}`,
  )
})

test('runtime manifest gate must exist before release packaging is considered complete', () => {
  const manifestCandidates = [
    'docs/registry/RUNTIME_MANIFEST.md',
    'src-tauri/resources/runtime/manifest.json',
    'scripts/preflight-runtime-manifest.mjs',
  ]
  const existing = manifestCandidates.filter(fileExists)

  assert.notEqual(
    existing.length,
    0,
    `${policyStatement.expectedGapLabel}: runtime manifest missing; future gate must record runtime version/hash/source/allowed_in_portable`,
  )
})

test('contract guard does not import dev-api, business source, or read runtime data secrets', () => {
  assert.ok(policyStatement.rules.includes('Do not import scripts/dev-api.js.'))
  assert.ok(policyStatement.rules.includes('Do not read runtime/data/secrets content.'))
  assert.ok(policyStatement.rules.includes('Do not run package or build commands.'))

  const thisTest = readText('tests/contract/runtime-packaging-gate.test.js')
  const devApiFileName = ['dev', 'api'].join('-') + '.js'
  const forbiddenDevApiImports = [
    `from '../../scripts/${devApiFileName}'`,
    `from '../scripts/${devApiFileName}'`,
    `import './scripts/${devApiFileName}'`,
  ]
  for (const forbiddenImport of forbiddenDevApiImports) {
    assert.equal(thisTest.includes(forbiddenImport), false)
  }
  const forbiddenRuntimeSecretPath = ['src-tauri', 'resources', 'data', 'hermes', '.env'].join('/')
  const forbiddenRelayConfigName = ['relay', 'config'].join('-') + '.json"'
  assert.equal(thisTest.includes(forbiddenRuntimeSecretPath), false)
  assert.equal(thisTest.includes(forbiddenRelayConfigName), false)
})
